### ISSUE TITLE
RegEx Replace Test

### ISSUE THREAD

**Issue by CKwan-hub** [CKwan-hub/SubStringExercise#2]
Hello, 

If you have some time to take a look at some non-functional code:

I have created a pull request with an additional function. 
In the "GETURL" function, I have added a RegEx looking for the same parameters that have been selected by the substring results:

var Reg = RegExp("([A-z]{9})+(\.[A-z]{3})");
BaseURL.replace(RegExp, "<span class = 'highlight'>"+$1+"</span>");
       
I wanted to replace the selected results in the original long URL and replace them with a highlighted class (but same text) that is highlighted yellow. 

This would give the effect of highlighting the selected parameters chosen by substring, but in actuality would be a Regular Expression seeking those same parameters. 

Nothing important, just practice. If you don't have time, not a problem!

**Comment by CKwan-hub** [comment]
Forgot to assign!

**Comment by dadkins20** [comment]
i may have some time tonight during the election.  i'll try to give it a
run.

David

**Comment by CKwan-hub** [comment]
Thanks. I thought it would be cool, since RegEx made sense, but never had a
chance to use it to implement or do anything in conjunction with other
functions and elements.
